package com.example.happypet.model

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "pets")
data class Pet(
    @PrimaryKey(autoGenerate = true) val id: Int = 0, // Default to 0 for autogenerated IDs
    val name: String,
    val age: Int,
    val breed: String,
    val animalType: String,
    val image: String
)


